FROM node:12-alpine

WORKDIR usr/src/app

COPY package.json /usr/src/app/package.json

# Json Web Token
ENV JWT_KEY=09tu%&^RH&UIK()*&%tufd2345oehgk@%t*&(dlkj)87675@#$%^

# Redis
ENV DB_NAME=bitgames
ENV DB_HOST=datastore
ENV DB_PORT=6379
ENV DB_PASS=de94hhty3jt@$#@%$r76587rt6tsd7&%$^#@$

RUN npm install
RUN npm install -g nodemon

CMD ["nodemon"]